# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'host_einstellungen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HostEinstellungenWindow(object):
    def setupUi(self, HostEinstellungenWindow):
        HostEinstellungenWindow.setObjectName("HostEinstellungenWindow")
        HostEinstellungenWindow.resize(319, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HostEinstellungenWindow.sizePolicy().hasHeightForWidth())
        HostEinstellungenWindow.setSizePolicy(sizePolicy)
        HostEinstellungenWindow.setMinimumSize(QtCore.QSize(319, 130))
        HostEinstellungenWindow.setMaximumSize(QtCore.QSize(319, 130))
        self.hostname_ip = QtWidgets.QLineEdit(HostEinstellungenWindow)
        self.hostname_ip.setGeometry(QtCore.QRect(110, 20, 189, 28))
        self.hostname_ip.setText("")
        self.hostname_ip.setObjectName("hostname_ip")
        self.label_hostname_ip = QtWidgets.QLabel(HostEinstellungenWindow)
        self.label_hostname_ip.setGeometry(QtCore.QRect(20, 25, 91, 16))
        self.label_hostname_ip.setObjectName("label_hostname_ip")
        self.retry = QtWidgets.QPushButton(HostEinstellungenWindow)
        self.retry.setGeometry(QtCore.QRect(110, 80, 90, 30))
        self.retry.setAutoFillBackground(False)
        self.retry.setCheckable(False)
        self.retry.setObjectName("retry")
        self.apply = QtWidgets.QPushButton(HostEinstellungenWindow)
        self.apply.setGeometry(QtCore.QRect(210, 80, 90, 30))
        self.apply.setAutoFillBackground(False)
        self.apply.setCheckable(False)
        self.apply.setObjectName("apply")
        self.label_falscher_hostname_ip = QtWidgets.QLabel(HostEinstellungenWindow)
        self.label_falscher_hostname_ip.setEnabled(True)
        self.label_falscher_hostname_ip.setGeometry(QtCore.QRect(20, 55, 281, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_falscher_hostname_ip.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_falscher_hostname_ip.setFont(font)
        self.label_falscher_hostname_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_falscher_hostname_ip.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_falscher_hostname_ip.setObjectName("label_falscher_hostname_ip")
        self.label_keine_verbindung = QtWidgets.QLabel(HostEinstellungenWindow)
        self.label_keine_verbindung.setGeometry(QtCore.QRect(20, 55, 281, 16))
        self.label_keine_verbindung.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keine_verbindung.setObjectName("label_keine_verbindung")

        self.retranslateUi(HostEinstellungenWindow)
        self.retry.clicked.connect(HostEinstellungenWindow.retry) # type: ignore
        self.apply.clicked.connect(HostEinstellungenWindow.apply) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HostEinstellungenWindow)
        HostEinstellungenWindow.setTabOrder(self.hostname_ip, self.apply)
        HostEinstellungenWindow.setTabOrder(self.apply, self.retry)

    def retranslateUi(self, HostEinstellungenWindow):
        _translate = QtCore.QCoreApplication.translate
        HostEinstellungenWindow.setWindowTitle(_translate("HostEinstellungenWindow", "Einstellung"))
        self.label_hostname_ip.setText(_translate("HostEinstellungenWindow", "Hostname/IP:"))
        self.retry.setText(_translate("HostEinstellungenWindow", "Wiederholen"))
        self.apply.setText(_translate("HostEinstellungenWindow", "Anwenden"))
        self.label_falscher_hostname_ip.setText(_translate("HostEinstellungenWindow", "Hostname/IP nicht valide!"))
        self.label_keine_verbindung.setText(_translate("HostEinstellungenWindow", "Verbindung fehlgeschlagen"))
